spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/srm_kart?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Security JWT configuration
srmkart.jwt.secret=9a67475df22d057134305885e3328e19e7a27a0503f8a0026e47dfcdc639352e
srmkart.jwt.expiration=86400000
